# Generated by Django 6.0.1 on 2026-01-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medicines",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("barnd", models.CharField(max_length=200)),
                ("description", models.TextField(max_length=1000)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("stock", models.PositiveIntegerField()),
                ("dosege", models.CharField(max_length=10)),
                ("required_prescriptions", models.BooleanField(default=False)),
                ("created_on", models.DateField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
