# Generated by Django 6.0.1 on 2026-02-02 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medicines", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="medicines",
            old_name="barnd",
            new_name="brand",
        ),
        migrations.RenameField(
            model_name="medicines",
            old_name="dosege",
            new_name="dosage",
        ),
    ]
